"""Synthesize a small test song so the pipeline can run end to end without Suno."""

from __future__ import annotations

import json

import numpy as np
import soundfile as sf

from .lyrics import parse
from .project import Project
from .schemas import SongSpec
from .stages.song import save

LYRICS = """[Intro - pads only]

[Verse 1 - close and quiet]
Porch light humming in the rain
Your coat still hanging by the door
I count the hours like the train
That doesn't stop here anymore

[Chorus - lift, open vowels]
Hold the li-ight
Hold it lo-ow
Carry me ho-ome
When the river's slow

[Outro - fading]

[End]"""


def build(p: Project, bpm: float = 96, sr: int = 44100) -> None:
    spec = SongSpec(title="Porch Light (demo)", style="Ambient folk ballad, 96 BPM. Soft male vocal. "
                    "Felt piano and warm pads. Brushed kit enters at the chorus. Ends on a held note.",
                    exclude="autotune, EDM", lyrics=LYRICS,
                    notes="Synthetic demo song generated by `songvid demo`.")
    save(p, spec, "Demo brief: a quiet song about waiting for someone to come home.")

    beat = 60 / bpm
    bar = beat * 4
    lines = parse(LYRICS)
    # layout: 4 bars intro, each line = 2 bars, 2 bars gap between sections, 4 bars outro
    t = 4 * bar
    word_times = []
    prev_sec = lines[0].section
    for ln in lines:
        if ln.section != prev_sec:
            t += 2 * bar
            prev_sec = ln.section
        n = len(ln.words)
        span = 2 * bar * 0.8
        for k, w in enumerate(ln.words):
            s = t + span * k / n
            word_times.append((w, s, s + span / n * 0.85))
        t += 2 * bar
    duration = t + 4 * bar
    n = int(duration * sr)
    tt = np.arange(n) / sr
    y = np.zeros(n)

    chorus_start = next(s for (w, s, e), ln in zip(word_times, [l for l in lines for _ in l.words])
                        if ln.section.startswith("Chorus"))
    # pads: chord per bar (Am F C G)
    roots = [220.0, 174.61, 261.63, 196.0]
    for b in range(int(duration / bar) + 1):
        a, z = int(b * bar * sr), min(n, int((b + 1) * bar * sr))
        if a >= n:
            break
        r = roots[b % 4]
        seg = tt[a:z] - tt[a]
        env = np.minimum(1, seg / 0.3) * np.minimum(1, (bar - seg) / 0.3)
        for mult in (1, 1.26, 1.5, 2):
            y[a:z] += 0.05 * np.sin(2 * np.pi * r * mult / 2 * tt[a:z]) * env
        # bass
        y[a:z] += 0.12 * np.sin(2 * np.pi * r / 4 * tt[a:z]) * env
    # drums from 2 bars before the chorus, kick on every beat, hat on offbeats
    for k in range(int(duration / beat)):
        s = k * beat
        if s < chorus_start - 2 * bar or s > duration - 2 * bar:
            continue
        a = int(s * sr)
        seg = np.arange(min(int(0.25 * sr), n - a)) / sr
        y[a:a + len(seg)] += 0.6 * np.sin(2 * np.pi * (50 + 80 * np.exp(-seg * 30)) * seg) * np.exp(-seg * 12)
        h = int((s + beat / 2) * sr)
        hs = np.arange(min(int(0.05 * sr), max(0, n - h))) / sr
        y[h:h + len(hs)] += 0.05 * np.random.default_rng(k).standard_normal(len(hs)) * np.exp(-hs * 80)
    # "vocal": a vibrato tone per word in the 300-900 Hz band
    melody = [440, 494, 523, 587, 523, 494, 440, 392]
    for i, (w, s, e) in enumerate(word_times):
        a, z = int(s * sr), int(e * sr)
        seg = tt[a:z] - s
        f0 = melody[i % len(melody)] * (1 + 0.01 * np.sin(2 * np.pi * 5.5 * seg))
        env = np.minimum(1, seg / 0.03) * np.minimum(1, (e - s - seg) / 0.05)
        y[a:z] += 0.2 * (np.sin(2 * np.pi * f0 * seg) + 0.3 * np.sin(4 * np.pi * f0 * seg)) * env
    y = y / (np.abs(y).max() + 1e-9) * 0.9
    sf.write(p.path("audio.wav"), y.astype(np.float32), sr)
    # Ground truth in Suno's aligned-words format, so the "suno" alignment path gets exercised.
    p.suno_aligned.write_text(json.dumps({"alignedWords": [
        {"word": w + " ", "success": True, "startS": round(s, 3), "endS": round(e, 3), "palign": 0}
        for w, s, e in word_times]}, indent=1))
    p.write(p.suno, {"mode": "manual", "clips": [{"id": "demo", "local_path": "audio.wav"}], "chosen": "demo"})
